import Navbar from "./_components/navbar";
import Footer from "./_components/footer";

export const metadata = {
  title: "PhytoScience",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
