import Navbar from "./_components/navbar";
import Footer from "./_components/footer";

export const metadata = {
    title: "PhytoScience",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <head>
                <link
                    href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
                    rel="stylesheet"
                />
            </head>
            <body>
                <Navbar />
                <div>{children}</div>
                <Footer />
                <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js" defer></script>
            </body>
        </html>
    );
}
